on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64, arm7]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: "arm64"
            goos: windows
          - goarch: "arm7"
            goos: windows
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.30
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 1.16
          project_path: "./pkg/cmd/grafana-kiosk"
          extra_files: LICENSE README.md
